### ISSUE TITLE
ImportError: cannot import name 'bigquery_storage' from 'google.cloud'

### ISSUE THREAD

**Issue by dqmota** [totvslabs/pyCarol#599]
MIssed `google-cloud-bigquery-storage` dependency while installing pycarol.
![Screenshot 2023-03-03 at 16 23 43](https://user-images.githubusercontent.com/12943808/222808795-449331be-ba36-41bf-a8dc-b38b1d95a086.png)
![Screenshot 2023-03-03 at 16 39 58](https://user-images.githubusercontent.com/12943808/222811503-7b709b37-3759-4dc5-95c5-b5d4d61e3ed0.png)

**Comment by darolt** [comment]
This issue is solved in version 2.54.14. It was not an issue for python 3.6 (that is usually where we run the tests), but it was a problem for python 3.11. For next releases we can include a test environment for many python versions. For more details please refer to https://totvslabs.atlassian.net/browse/DASC-1121.
